In [3]:
import torch
from torch import nn

def corr2d(X, K):
    h,w = K.shape
    Y = torch.zeros( (X.shape[0] - (h - 1),X.shape[1] - (w - 1)) )
    for i in range(Y.shape[0]):
        for j in range(Y.shape[1]):
            Y[i, j] = (X[i:i + h,j:j +w] * K).sum()
    return Y

class MyConv2d(nn.Module):

    def __init__(self,kernel,bias):
        super().__init__()
        self.weights = kernel
        self.bias = 0

    def forward(self, X):
        return corr2d(X, self.weights) + self.bias

X = torch.ones((6, 8))
X[:, 2:6] = 0
X

tensor([[1., 1., 0., 0., 0., 0., 1., 1.],
        [1., 1., 0., 0., 0., 0., 1., 1.],
        [1., 1., 0., 0., 0., 0., 1., 1.],
        [1., 1., 0., 0., 0., 0., 1., 1.],
        [1., 1., 0., 0., 0., 0., 1., 1.],
        [1., 1., 0., 0., 0., 0., 1., 1.]])

In [7]:
conv2d = MyConv2d( kernel=torch.tensor([[0., 1.],[0., 1.]]), bias= 0 )
conv2d.forward(X)

tensor([[2., 0., 0., 0., 0., 2., 2.],
        [2., 0., 0., 0., 0., 2., 2.],
        [2., 0., 0., 0., 0., 2., 2.],
        [2., 0., 0., 0., 0., 2., 2.],
        [2., 0., 0., 0., 0., 2., 2.]])

In [8]:
conv2d.forward(X.t())

tensor([[2., 2., 2., 2., 2.],
        [1., 1., 1., 1., 1.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [1., 1., 1., 1., 1.],
        [2., 2., 2., 2., 2.]])

In [9]:
conv2d = MyConv2d( kernel=torch.tensor([[0., 1.],[0., 1.]]).t(), bias= 0 )
conv2d.forward(X)

tensor([[2., 1., 0., 0., 0., 1., 2.],
        [2., 1., 0., 0., 0., 1., 2.],
        [2., 1., 0., 0., 0., 1., 2.],
        [2., 1., 0., 0., 0., 1., 2.],
        [2., 1., 0., 0., 0., 1., 2.]])

In [11]:
X

tensor([[1., 1., 0., 0., 0., 0., 1., 1.],
        [1., 1., 0., 0., 0., 0., 1., 1.],
        [1., 1., 0., 0., 0., 0., 1., 1.],
        [1., 1., 0., 0., 0., 0., 1., 1.],
        [1., 1., 0., 0., 0., 0., 1., 1.],
        [1., 1., 0., 0., 0., 0., 1., 1.]])