# 数学基础 —— 概率论

本次课程学习的是概率论相关的知识。


In [1]:
import torch
# distributions 分布
# multinomial 多项式
from torch.distributions import multinomial

## 掷骰子采样

我们先进行一个简单的采样实验 —— 掷骰子，我们知道掷骰子的每面出现的概率为 $\frac{1}{6}$ ，我们在此使用一个概率向量来模拟这一情形，即我们用一个 6 维的向量，其每一个元素都是对应面出现的概率，然后我们再进行采样。

In [2]:
# 这里模拟的是一个投骰子的的概率，即每个面上的概率为 1/6
fair_probs = torch.ones(6,dtype=torch.float32)/6
# 这里是采样过程，在投骰子的概率分布上采10次样， sample 采样
result = multinomial.Multinomial(10,fair_probs).sample()
print(result)

tensor([3., 1., 1., 2., 2., 1.])


在进行采样后，我们可以求其每一个面出现的频率

In [4]:
count = 1000
result = multinomial.Multinomial(count,fair_probs).sample()
print(result / count)

tensor([0.1630, 0.1760, 0.1810, 0.1730, 0.1680, 0.1390])


我们通过求其频率发现，每个面出现的概率是接近 $\frac{1}{6}$ 的，即接近 0.167。下面我们进行 500 组实验，每次实验我们都掷 10 次骰子。

In [6]:
count = 10
batch = 500
result = multinomial.Multinomial(count,fair_probs).sample((batch,))
print(result)

tensor([[2., 3., 2., 3., 0., 0.],
        [3., 0., 3., 1., 2., 1.],
        [1., 2., 2., 2., 2., 1.],
        ...,
        [1., 2., 4., 1., 1., 1.],
        [2., 2., 3., 1., 0., 2.],
        [4., 2., 1., 0., 0., 3.]])


我们现在得到的结果是一个 10 * 500 的矩阵，我们可以绘制一张图以查看随着时间（投掷批次）的增加，其频率是如何收敛于真实概率的。

In [37]:
seq = result.cumsum(dim = 0)
count_matrix = torch.arange(count,(batch + 1) *count,count).reshape(1,batch).T.repeat(1,6)
print(seq / count_matrix)

tensor([[0.2000, 0.3000, 0.2000, 0.3000, 0.0000, 0.0000],
        [0.2500, 0.1500, 0.2500, 0.2000, 0.1000, 0.0500],
        [0.2000, 0.1667, 0.2333, 0.2000, 0.1333, 0.0667],
        ...,
        [0.1624, 0.1667, 0.1699, 0.1669, 0.1677, 0.1665],
        [0.1625, 0.1667, 0.1701, 0.1667, 0.1673, 0.1665],
        [0.1630, 0.1668, 0.1700, 0.1664, 0.1670, 0.1668]])
